version: "3.6"

services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile.build
    environment:
      - WEB_PORT=${WEB_PORT_HTTP}
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - "./caddy/web:/app/build"
    command: "npm run build"

