version: '3'

services:
  caddy:
    image: caddy:2.3.0
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - ./config/caddy_data:/data
      - ./config/caddy_config:/config
    networks:
      web-network:
        ipv4_address: 192.168.10.2

#--------------------

networks:
    web-network:
      external: true